---
search:
    keywords: ['exception','异常']

---


# 当一个方法在运行过程中产生一个异常，则这个方法会终止，但是整个程序不一定终止运行。这句话是否正确？

# 参考解答

正确； 产生异常时，方法的调用终止，程序会返回到方法调用点，这时如果调用者使用了try catch来处理了这个异常，则整个程序可以恢复运行。

---
